@startuml
class com.example.itamusic.ChordLessonActivity {
~ TextView tvInfo
~ ImageButton btnProfileActivity
# void onCreate(Bundle)
}


class com.example.itamusic.GuitarActivity {
~ ImageButton btnEm
- Guitar guitar
# void onCreate(Bundle)
}


class com.example.itamusic.DrumsActivity {
~ ImageButton btnRide
- Drums drums
# void onCreate(Bundle)
}


class com.example.itamusic.IntervalLessonActivity {
~ TextView tvInfo
~ ImageButton btnProfileActivity
# void onCreate(Bundle)
}


class com.example.itamusic.ProfileActivity {
- TextView tvUserName
- ImageButton btnGoBack
- User user
- FirebaseHelper firebaseHelper
# void onCreate(Bundle)
- void updateUI()
}


class com.example.itamusic.TunerActivity {
~ TextView tvPitch
~ ImageButton btnProfileActivity
# void onCreate(Bundle)
+ void processPitch(float)
}


class com.example.itamusic.NoteTestActivity {
~ ImageButton btnAnswer1
~ TextView tvAnswer1
- Piano piano
- ArrayList<TextView> textViewList
- ArrayList<ImageButton> ButtonList
- int counter
- User user
- FirebaseHelper firebaseHelper
# void onCreate(Bundle)
+ void nextQuestion()
+ void checkAnswer(ArrayList<ImageButton>)
}


class com.example.itamusic.ChatBotActivity {
- RecyclerView chatRecyclerView
- ChatAdapter chatAdapter
- List<Message> chatMessages
- EditText etUserInput
- Button btnSend
- ImageButton btnProfileActivity
- OkHttpClient client
- {static} MediaType JSON
- {static} String API_URL
- {static} String API_KEY
# void onCreate(Bundle)
- void addMessage(Message)
- void sendMessageToAPI(String)
}


class com.example.itamusic.Message {
~ String text
~ boolean isUser
}

class com.example.itamusic.Stats {
- int intervalListeningQuestions
- int intervalListeningCorrect
- int noteListeningQuestions
- int noteListeningCorrect
- int chordProgressionQuestions
- int chordProgressionCorrect
- int noteReadingQuestions
- int noteReadingCorrect
+ void incrementIntervalListeningQuestions(boolean)
+ void incrementNoteListeningQuestions(boolean)
+ void incrementChordProgressionQuestions(boolean)
+ void incrementNoteReadingQuestions(boolean)
+ int getIntervalListeningQuestions()
+ int getIntervalListeningCorrect()
+ int getNoteListeningQuestions()
+ int getNoteListeningCorrect()
+ int getChordProgressionQuestions()
+ int getChordProgressionCorrect()
+ int getNoteReadingQuestions()
+ int getNoteReadingCorrect()
+ double getIntervalListeningSuccessRate()
+ double getNoteListeningSuccessRate()
+ double getChordProgressionSuccessRate()
+ double getNoteReadingSuccessRate()
- double calculateSuccessRate(int,int)
}


class com.example.itamusic.NotesView {
- Paint paint
- Paint notePaint
- Paint textPaint
- List<String> notes
- int startY
- int lineSpacing
- int staffWidth
- void init(Context)
# void onDraw(Canvas)
- void drawTrebleSign(Canvas)
- void drawNote(Canvas,String,int)
- void drawWholeNoteSymbol(Canvas,int,int)
- int getPitchPosition(String)
+ void addNote(String)
+ void clearNotes()
}


abstract class com.example.itamusic.Instrument {
# String name
# ArrayList<Note> notesList
+ String getName()
+ void setName(String)
+ ArrayList<Note> getNotesList()
+ void setNotesList(ArrayList<Note>)
+ ArrayList<String> getNotesNamesList()
+ void play(String)
}


class com.example.itamusic.FirebaseHelper {
- {static} String TAG
- DatabaseReference database
+ DatabaseReference getDatabase()
+ void uploadUserData(User)
+ void uploadUserStats(String,Stats)
+ void getUserById(String,UserCallback)
+ void getAllUsers(UsersCallback)
}


interface com.example.itamusic.FirebaseHelper$UserCallback {
~ void onUserReceived(User)
}

interface com.example.itamusic.FirebaseHelper$UsersCallback {
~ void onUsersReceived(ArrayList<User>)
}

class com.example.itamusic.Interval {
- Note note1
- Note note2
- int halfTones
+ Note getNote1()
+ void setNote1(Note)
+ Note getNote2()
+ void setNote2(Note)
+ int getHalfTones()
+ void setHalfTones(int)
+ void play()
+ void play(int)
}


class com.example.itamusic.Guitar {
- String name
- ArrayList<Note> chordsList
- Note EmChord
+ ArrayList<Note> getChordsList()
+ ArrayList<String> getChordsNamesList()
+ void playGuitarChord(String)
}


class com.example.itamusic.ChatAdapter {
- List<Message> messages
- Context context
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemViewType(int)
+ int getItemCount()
- void copyToClipboard(String)
}


class com.example.itamusic.ChatAdapter$ViewHolder {
~ TextView messageText
}

class com.example.itamusic.HomeActivity {
~ ImageButton btnInstrumentsActivity
# void onCreate(Bundle)
}


class com.example.itamusic.IntervalTestActivity {
~ ImageButton btnAnswer1
~ TextView tvAnswer1
- Piano piano
- ArrayList<TextView> textViewList
- ArrayList<ImageButton> ButtonList
- int counter
- User user
- FirebaseHelper firebaseHelper
# void onCreate(Bundle)
+ void nextQuestion()
+ void checkAnswer(ArrayList<ImageButton>)
}


class com.example.itamusic.ExercisesMenuActivity {
~ ImageButton btnIntervalsActivity
# void onCreate(Bundle)
}


class com.example.itamusic.PianoActivity {
~ Button c4
~ ImageButton btnProfileActivity
- Piano piano
# void onCreate(Bundle)
}


class com.example.itamusic.Drums {
- String name
- ArrayList<Note> notesList
- Note ride
+ ArrayList<Note> getNotesList()
+ ArrayList<String> getNotesNamesList()
+ void playDrumsNote(String)
}


class com.example.itamusic.User {
- String name
- String id
- String userName
- String password
- Stats stats
+ String getName()
+ void setName(String)
+ String getId()
+ void setId(String)
+ String getUserName()
+ void setUserName(String)
+ String getPassword()
+ void setPassword(String)
+ Stats getStats()
+ void setStats(Stats)
}


class com.example.itamusic.SettingsActivity {
~ ImageButton btnChangePic
# void onCreate(Bundle)
}


class com.example.itamusic.Note {
- String name
- int address
- float leftVol
- float rightVol
- int priority
- int loop
- float rate
- SoundPool mSoundPool
- Context context
- int sound
- int halfTones
+ String getName()
+ void setName(String)
+ int getAddress()
+ void setAddress(int)
+ float getLeftVol()
+ void setLeftVol(float)
+ float getRightVol()
+ void setRightVol(float)
+ int getPriority()
+ void setPriority(int)
+ int getLoop()
+ void setLoop(int)
+ float getRate()
+ void setRate(float)
+ Context getContext()
+ void setContext(Context)
+ int getSound()
+ void setSound(int)
+ int getHalfTones()
+ void setHalfTones(int)
+ void play()
+ void play(int)
}


class com.example.itamusic.LessonsMenuActivity {
~ ImageButton btnIntervalsActivity
# void onCreate(Bundle)
}


class com.example.itamusic.NoteLessonActivity {
~ TextView tvInfo
~ ImageButton btnProfileActivity
# void onCreate(Bundle)
}


class com.example.itamusic.DrawActivity {
# void onCreate(Bundle)
}

class com.example.itamusic.KeyLessonActivity {
~ TextView tvInfo
~ ImageButton btnProfileActivity
# void onCreate(Bundle)
}


class com.example.itamusic.InstrumentsMenuActivity {
~ ImageButton btnPianoActivity
# void onCreate(Bundle)
}


class com.example.itamusic.MainActivity {
~ Button btnSignUp
~ ImageButton btnLogIn
~ EditText etName
~ Dialog signUpDialog
- ArrayList<User> users
- FirebaseHelper firebaseHelper
# void onCreate(Bundle)
+ void createSignUpDialog()
- boolean checkUserLogIn(String,String)
+ boolean checkUserSignUp(String,String,String)
- User getUserByLogIn(String,String)
}


class com.example.itamusic.Piano {
- String name
- ArrayList<Note> notesList
- Note cNote
+ ArrayList<Note> getNotesList()
+ ArrayList<String> getNotesNamesList()
+ void playPianoNote(String)
}




androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.ChordLessonActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.GuitarActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.DrumsActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.IntervalLessonActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.ProfileActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.TunerActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.NoteTestActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.ChatBotActivity
java.io.Serializable <|.. com.example.itamusic.Stats
android.view.View <|-- com.example.itamusic.NotesView
com.example.itamusic.FirebaseHelper +.. com.example.itamusic.FirebaseHelper$UserCallback
com.example.itamusic.FirebaseHelper +.. com.example.itamusic.FirebaseHelper$UsersCallback
com.example.itamusic.Instrument <|-- com.example.itamusic.Guitar
com.example.itamusic.Adapter <|-- com.example.itamusic.ChatAdapter
com.example.itamusic.ChatAdapter +.. com.example.itamusic.ChatAdapter$ViewHolder
com.example.itamusic.ViewHolder <|-- com.example.itamusic.ChatAdapter$ViewHolder
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.HomeActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.IntervalTestActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.ExercisesMenuActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.PianoActivity
com.example.itamusic.Instrument <|-- com.example.itamusic.Drums
java.io.Serializable <|.. com.example.itamusic.User
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.SettingsActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.LessonsMenuActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.NoteLessonActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.DrawActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.KeyLessonActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.InstrumentsMenuActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.itamusic.MainActivity
com.example.itamusic.Instrument <|-- com.example.itamusic.Piano
@enduml